site_name: Polygon Hermez Documentation
site_url: https://docs.hermez.io/
theme:
  name: material
  palette:
    primary: deep purple
  logo: logo-white.svg
  favicon: favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
repo_url: https://github.com/hermeznetwork/hermez-docs
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/polygonhermez
    - icon: fontawesome/brands/github
      link: https://github.com/hermeznetwork/hermez-docs
    - icon: octicons/browser-24
      link: https://hermez.io/

nav:
  - Polygon zkEVM:
    - Basic Concepts:
      - Introduction: "zkEVM/Basic-Concepts/introduction.md"
      - "First Example: Fibonacci": "zkEVM/Basic-Concepts/fibonacci.md"
      - Simple State Machine: "zkEVM/Basic-Concepts/simple-state-machine.md"  
      - Modular Design: "zkEVM/Basic-Concepts/modular-design.md"  
    - Architecture:
      - zkProver: "zkEVM/Architecture/zkProver.md"
    - zkASM:
      - Introduction: "zkEVM/zkASM/introduction.md"
      - Basic Syntax: "zkEVM/zkASM/basic-syntax.md"
      - Some Examples: "zkEVM/zkASM/some-examples.md"
      - Related Repositories: "zkEVM/zkASM/related-repos.md"
    - PIL:
      - Introduction: "zkEVM/PIL/introduction.md"
      - Hello Word Examples: "zkEVM/PIL/hello-world-examples.md"
      - Components: "zkEVM/PIL/components.md"
      - Cyclical Nature: "zkEVM/PIL/cyclical-nature.md"
      - Modularity: "zkEVM/PIL/modularity.md"
      - Advanced Features: "zkEVM/PIL/advanced-features.md"
      - Related Repositories: "zkEVM/PIL/related-repos.md"
    - State Machines:
      - Arithmetic: "zkEVM/State-Machines/Arithmetic/Arithmetic-State-Machine-typ.md"
      - Storage: "zkEVM/State-Machines/Storage/Storage-State-Machine-typ.md"
      - Hashing: "zkEVM/State-Machines/Hashing/Hashing-State-Machine-typ.md"
      - Binary: "zkEVM/State-Machines/Binary/Binary-State-Machine-typ.md"
      - Memory: "zkEVM/State-Machines/Memory/memory-state-machine.md"
      - Memory Align: "zkEVM/State-Machines/Memory-Align/memory-align-state-machine.md"
      - Complementaries: "zkEVM/State-Machines/Complementary/complementary-state-machines.md"
      - Configuration File: "zkEVM/State-Machines/Complementary/configuration-file.md"
    # - Tools & Optimizations:
    #   - Merkle Tree: "zkEVM/tools-optimizations/merkle-tree.md"
    # - References: "zkEVM/references.md"

  - Polygon Hermez 1.0:
    - About:
      - Ethereum Scalability and zk-Rollups: "Hermez_1.0/about/scalability.md"
      - Polygon Hermez Value Proposition: "Hermez_1.0/about/value-proposition.md"
      - Polygon Hermez Network Model: "Hermez_1.0/about/model.md"
      - Security: "Hermez_1.0/about/security.md"
    - Users:
      - Polygon Hermez Wallet: "Hermez_1.0/users/hermez-wallet.md"
      - Polygon Hermez Mainnet: "Hermez_1.0/users/mainnet.md"
      - Polygon Hermez Testnet: "Hermez_1.0/users/testnet.md"
      - Exchanges: "Hermez_1.0/users/exchanges.md"
    - Developers:
      - Developer Guide: "Hermez_1.0/developers/dev-guide.md"
      - Protocol:
        - Polygon Hermez zkRollup protocol:
          - Core protocol: "Hermez_1.0/developers/protocol/hermez-protocol/protocol.md"
          - Smart contracts: "Hermez_1.0/developers/protocol/hermez-protocol/contracts/contracts.md"
          - Circuits: "Hermez_1.0/developers/protocol/hermez-protocol/circuits/circuits.md"
        - Forging consensus protocol: "Hermez_1.0/developers/protocol/consensus/consensus.md"
        - Withdrawal delayer protocol: "Hermez_1.0/developers/protocol/withdrawal-delayer/withdrawal-delayer.md"
      - Examples/SDK: "Hermez_1.0/developers/sdk.md"
      - API: "Hermez_1.0/developers/api.md"
      - Batch Explorer: "Hermez_1.0/developers/batch-explorer.md"
      - Polygon Hermez NodePrice Updater: "Hermez_1.0/developers/price-updater.md"
      - Glossary: "Hermez_1.0/developers/glossary.md"
    - FAQ:
      - End-Users: "Hermez_1.0/faq/end-users.md"
      - Integrators: "Hermez_1.0/faq/integrators.md"
      - Coordinators: "Hermez_1.0/faq/coordinators.md"
      - Proof of Donation: "Hermez_1.0/faq/pod.md"
      - Other: "Hermez_1.0/faq/other.md"
